# Generated by Django 3.0.8 on 2020-07-17 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.CharField(max_length=200)),
                ('listing_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True)),
                ('contact_date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 16, 21, 16, 34, 107072))),
                ('user_id', models.IntegerField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Context',
            },
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
